// Logotip fayllari (logoData/<liga papkasi>/<fayl>.png) -> o'yindagi klub id'si.
// Yangi logotip qo'shish: faylni tegishli liga papkasiga tashlang va shu yerga
// "papka/fayl nomi (kengaytmasiz)": "klub_id" qatorini qo'shing.
// Eslatma: papka ichida fayl nomi klub id'siga TENG bo'lsa (masalan real_madrid.png), moslash shart emas.
module.exports = {
  // ---- Premier League (Apl) ----
  'Apl/afc_bournemouth': 'bournemouth',
  'Apl/arsenal': 'arsenal',
  'Apl/aston_villa': 'aston_villa',
  'Apl/brentford': 'brentford',
  'Apl/brighton_hove_albion': 'brighton',
  'Apl/chelsea': 'chelsea',
  'Apl/coventry_city': 'coventry',
  'Apl/crystal_palace': 'crystal_palace',
  'Apl/everton': 'everton',
  'Apl/fulham': 'fulham',
  'Apl/hull_city': 'hull',
  'Apl/ipswich': 'ipswich',
  'Apl/leeds_united': 'leeds',
  'Apl/liverpool': 'liverpool',
  'Apl/manchester_city': 'manchester_city',
  'Apl/manchester_united': 'man_utd',
  'Apl/newcastle': 'newcastle',
  'Apl/nottinhem_forest': 'nottingham_forest',
  'Apl/sunderland': 'sunderland',
  'Apl/tottenham_hotspur': 'tottenham',
  // ---- Bundesliga ----
  'Bundesliga/augsburg': 'augsburg',
  'Bundesliga/bayer_leverkusen': 'leverkusen',
  'Bundesliga/bayern_munich': 'bayern-munchen',
  'Bundesliga/borussia_dortmund': 'dortmund',
  'Bundesliga/borussia_monchengladbach': 'gladbach',
  'Bundesliga/elversberg': 'elversberg',
  'Bundesliga/frankfurt': 'eintracht_frankfurt',
  'Bundesliga/freiburg': 'freiburg',
  'Bundesliga/hamburger': 'hamburger_sv',
  'Bundesliga/hoffenheim': 'hoffenheim',
  'Bundesliga/koln': 'fc_koln',
  'Bundesliga/mainz': 'mainz',
  'Bundesliga/paderborn': 'paderborn',
  'Bundesliga/rb_leipzig': 'rb_leipzig',
  'Bundesliga/schalke': 'schalke',
  'Bundesliga/stuttgart': 'stuttgart',
  'Bundesliga/union_berlin': 'union_berlin',
  'Bundesliga/werder_bremen': 'werder_bremen',
  // ---- Serie A ----
  'a seriya/ac milan': 'milan',
  'a seriya/atalanta': 'atalanta',
  'a seriya/bologna': 'bologna',
  'a seriya/cagliari': 'cagliari',
  'a seriya/como': 'como',
  'a seriya/fiorentina': 'fiorentina',
  'a seriya/frosinone': 'frosinone',
  'a seriya/genoa': 'genoa',
  'a seriya/inter milan': 'inter',
  'a seriya/juventus': 'juventus',
  'a seriya/lazio': 'lazio',
  'a seriya/lecce': 'lecce',
  'a seriya/monza': 'monza',
  'a seriya/napoli': 'napoli',
  'a seriya/parma': 'parma',
  'a seriya/roma': 'roma',
  'a seriya/sassuolo': 'sassuolo',
  'a seriya/torino': 'torino',
  'a seriya/udinese': 'udinese',
  'a seriya/venezia': 'venezia',
  // ---- La Liga ----
  'laliga/ateltic_bilbao': 'athletic_bilbao',
  'laliga/atletico_madrid': 'atletico_madrid',
  'laliga/barcelona': 'barcelona',
  'laliga/celta_vigo': 'celta_vigo',
  'laliga/deportivo': 'deportivo_coruna',
  'laliga/deportivo_alaves': 'alaves',
  'laliga/elche': 'elche',
  'laliga/getafe': 'getafe',
  'laliga/levante': 'levante',
  'laliga/malaga': 'malaga',
  'laliga/osasuna': 'osasuna',
  'laliga/racing_club': 'racing_santander',
  'laliga/rayo_vallecano': 'rayo_vallecano',
  'laliga/rcd_espanyol': 'espanyol',
  'laliga/real_betis': 'real_betis',
  'laliga/real_madrid': 'real_madrid',
  'laliga/real_socedad': 'real_sociedad',
  'laliga/sevilla': 'sevilla',
  'laliga/valencia': 'valencia',
  'laliga/villareal': 'villarreal',
  // ---- Ligue 1 ----
  'ligue 1/angers': 'angers',
  'ligue 1/auxerre': 'auxerre',
  'ligue 1/estac troyes': 'troyes',
  'ligue 1/le havre': 'le_havre',
  'ligue 1/le mans': 'le_mans',
  'ligue 1/lens': 'lens',
  'ligue 1/lille': 'lille',
  'ligue 1/lorient': 'lorient',
  'ligue 1/lyon': 'lyon',
  'ligue 1/marseille': 'marseille',
  'ligue 1/monaco': 'monaco',
  'ligue 1/nice': 'nice',
  'ligue 1/paris fc': 'paris_fc',
  'ligue 1/psg': 'psg',
  'ligue 1/stade brestois': 'brest',
  'ligue 1/stade rennais': 'rennes',
  'ligue 1/strasbourg': 'strasbourg',
  'ligue 1/toulouse': 'toulouse',
};
